version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drillflow

  redis:
    image: redis:alpine